{
 "title": "Epipe",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "epipe",
    "label": "Epipe",
    "query": "label_values(epipe_num_added_datasets,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Datasets stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "epipe_num_added_datasets{instance=\"$epipe\"}",
     "legendFormat": "Add - {{ scope }}"
    },
    {
     "expr": "epipe_num_deleted_datasets{instance=\"$epipe\"}",
     "legendFormat": "Del - {{ scope }}"
    }
   ]
  },
  {
   "title": "Projects stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "epipe_num_added_projects{instance=\"$epipe\"}",
     "legendFormat": "Add - {{ scope }}"
    },
    {
     "expr": "epipe_num_deleted_projects{instance=\"$epipe\"}",
     "legendFormat": "Del - {{ scope }}"
    }
   ]
  },
  { "title": "File system", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "epipe_fs_up_seconds{instance=\"$epipe\"}"
    }
   ]
  },
  {
   "title": "Event queue length",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "epipe_fs_event_queue_length{instance=\"$epipe\"}"
    }
   ]
  },
  {
   "title": "Elastic connection failed since",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "epipe_fs_elastic_connection_failed_since_seconds{instance=\"$epipe\"}"
    }
   ]
  },
  {
   "title": "Processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "epipe_fs_num_processed_events{instance=\"$epipe\"}",
     "legendFormat": "Event-{{ scope }}"
    },
    {
     "expr": "epipe_fs_num_processed_batches{instance=\"$epipe\"}",
     "legendFormat": "Batch-{{ scope }}"
    }
   ]
  },
  {
   "title": "Total time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "epipe_fs_avg_total_time_per_event_milliseconds{instance=\"$epipe\"}",
     "legendFormat": "Event-{{ scope }}"
    },
    {
     "expr": "epipe_fs_avg_total_time_per_batch_milliseconds{instance=\"$epipe\"}",
     "legendFormat": "Batch-{{ scope }}"
    }
   ]
  },
  {
   "title": "Event batching",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "epipe_fs_avg_batching_time_milliseconds{instance=\"$epipe\"}",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  {
   "title": "Ndb Processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "epipe_fs_avg_ndb_processing_time_milliseconds{instance=\"$epipe\"}",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  {
   "title": "Elastic batching time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "epipe_fs_avg_elastic_batching_time_milliseconds{instance=\"$epipe\"}",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  {
   "title": "Elastic bulk request time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "epipe_fs_avg_elastic_bulk_req_time_milliseconds{instance=\"$epipe\"}",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  { "title": "File provenance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "epipe_file_prov_up_seconds{instance=\"$epipe\"}"
    }
   ]
  },
  {
   "title": "Event queue length",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "epipe_file_prov_event_queue_length{instance=\"$epipe\"}"
    }
   ]
  },
  {
   "title": "Elastic connection failed since",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 31 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "epipe_file_prov_elastic_connection_failed_since_seconds{instance=\"$epipe\"}"
    }
   ]
  },
  {
   "title": "Processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "epipe_file_prov_num_processed_events{instance=\"$epipe\"}",
     "legendFormat": "Event-{{ scope }}"
    },
    {
     "expr": "epipe_file_prov_num_processed_batches{instance=\"$epipe\"}",
     "legendFormat": "Batch-{{ scope }}"
    }
   ]
  },
  {
   "title": "Total time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "epipe_file_prov_avg_total_time_per_event_milliseconds{instance=\"$epipe\"}",
     "legendFormat": "Event-{{ scope }}"
    },
    {
     "expr": "epipe_file_prov_avg_total_time_per_batch_milliseconds{instance=\"$epipe\"}",
     "legendFormat": "Batch-{{ scope }}"
    }
   ]
  },
  {
   "title": "Event batching",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "epipe_file_prov_avg_batching_time_milliseconds{instance=\"$epipe\"}",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  {
   "title": "Ndb Processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "epipe_file_prov_avg_ndb_processing_time_milliseconds{instance=\"$epipe\"}",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  {
   "title": "Elastic batching time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "epipe_file_prov_avg_elastic_batching_time_milliseconds{instance=\"$epipe\"}",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  {
   "title": "Elastic bulk request time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "epipe_file_prov_avg_elastic_bulk_req_time_milliseconds{instance=\"$epipe\"}",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  { "title": "App provenance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 52 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "epipe_app_prov_up_seconds{instance=\"$epipe\"}"
    }
   ]
  },
  {
   "title": "Event queue length",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 52 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "epipe_app_prov_event_queue_length{instance=\"$epipe\"}"
    }
   ]
  },
  {
   "title": "Elastic connection failed since",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 52 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "epipe_app_prov_elastic_connection_failed_since_seconds{instance=\"$epipe\"}"
    }
   ]
  },
  {
   "title": "Processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "epipe_app_prov_num_processed_events{instance=\"$epipe\"}",
     "legendFormat": "Event-{{ scope }}"
    },
    {
     "expr": "epipe_app_prov_num_processed_batches{instance=\"$epipe\"}",
     "legendFormat": "Batch-{{ scope }}"
    }
   ]
  },
  {
   "title": "Total time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "epipe_app_prov_avg_total_time_per_event_milliseconds{instance=\"$epipe\"}",
     "legendFormat": "Event-{{ scope }}"
    },
    {
     "expr": "epipe_app_prov_avg_total_time_per_batch_milliseconds{instance=\"$epipe\"}",
     "legendFormat": "Batch-{{ scope }}"
    }
   ]
  },
  {
   "title": "Event batching",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "epipe_app_prov_avg_batching_time_milliseconds{instance=\"$epipe\"}",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  {
   "title": "Ndb Processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 64 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "epipe_app_prov_avg_ndb_processing_time_milliseconds{instance=\"$epipe\"}",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  {
   "title": "Elastic batching time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "epipe_app_prov_avg_elastic_batching_time_milliseconds{instance=\"$epipe\"}",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  {
   "title": "Elastic bulk request time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 64 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "epipe_app_prov_avg_elastic_bulk_req_time_milliseconds{instance=\"$epipe\"}",
     "legendFormat": "{{ scope }}"
    }
   ]
  }
 ]
}